[build]
  command = "pip install -r requirements.txt"
  publish = "app/static"
  functions = "functions"

[functions]
  included_files = ["app/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
